

FROM openjdk:11

# Set the working directory
WORKDIR /app

# Copy necessary files
COPY qualitytrainingforwine.jar /app/qualitytrainingforwine.jar

# Expose any necessary ports
EXPOSE 8080

# Define the command to start the Java application
CMD ["java", "-jar", "qualitytrainingforwine.jar"]
